### ISSUE TITLE
Move TeamComponent to People Page

### ISSUE THREAD

**Issue by VeeIsForVanana** [up-csi/up-csi.github.io#74]

**Comment by ehrelevant** [comment]
**Add a method for switching between .bex and .exe in the People page** — With the transition to a new executive board, we’ll soon be adding .bex on the page. That said, we shouldn’t forget the contributions of the previous executives in making UP CSI what it is today. That’s why we should have a way to see the current and past executive board.
- This addition will also be used to hopefully display past executive boards prior to 2324 in the future as well as future executive boards, but for now focus on just 2324 and 2425.
- Consider implementing this with a dropdown menu, as previously suggested, so that when we start adding other executive boards it doesn’t make the page too cluttered.
- As for the pictures of .bex, it'll be fine if you use placeholders for now. Though, will check if we already have some ready.

**Comment by ehrelevant** [comment]
@ehrelevant — It has seemed rather strange that the About page contained the people of UP CSI instead of the People page, so why don’t we move this component? 
- Since this task is rather simple, I'll also incorporate the changes we did earlier in `EventsPanel` (putting the “JSON” into a `ts` file) and try adding some other improvements the component.
