### ISSUE TITLE
Add a way to switch between .bex and .exe from the Teams panel

### ISSUE THREAD

**Issue by VeeIsForVanana** [up-csi/up-csi.github.io#75]

**Comment by ehrelevant** [comment]
@galierie — With the transition to a new executive board, we’ll soon be adding .bex on the page. That said, we shouldn’t forget the contributions of the previous executives in making UP CSI what it is today. That’s why we should have a way to see the current and past executive board.
- This addition will also be used to hopefully display past executive boards prior to 2324 in the future as well as future executive boards, but for now focus on just 2324 and 2425.
- Consider implementing this with a dropdown menu, as previously suggested, so that when we start adding other executive boards it doesn’t make the page too cluttered.
- As for the pictures of .bex, it's fine if you use placeholders for now.

**Comment by ehrelevant** [comment]
Completed in #79.
